version: "2.1"

jobs:
  test:
    docker:
      - image: circleci/node:14.15.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install server
          command: npm install
      - run:
          name: Launch test
          command: npm run test
  build-docker-image:
    docker:
      - image: circleci/node:14.15.0
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Login to Scaleway image registry
          command: docker login rg.fr-par.scw.cloud/clement-registry -u nologin -p $SCW_SECRET_KEY
      - run:
          name: Build docker image
          command: docker build -t rg.fr-par.scw.cloud/clement-registry/tmpl-nest .
      - run:
          name: Push image to registry
          command: docker push rg.fr-par.scw.cloud/clement-registry/tmpl-nest
  deploy:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - run:
          name: Launch deploy
          command: ssh -o StrictHostKeyChecking=no root@163.172.190.45 sh deploy.sh rg.fr-par.scw.cloud/clement-registry/tmpl-nest 3000

workflows:
  version: "2"
  build:
    jobs:
      - test
      - build-docker-image:
          requires:
            - test
      - deploy:
          requires:
            - build-docker-image